#VARIABLES => A VARIABLE IS NAME OF MEMORY LOCATION WHERE WE STORE DATA.
name = "Rajveer"
age = 23
price = 580.0
print("my name is",name,"my age is",age)

#DATATYPE => DATATYPE SPECIFIES THE SIZE AND TYPE VALUE OF DATA.(INTEGERS , STRING , FLOAT , BOOLEAN , NONE).

#KEYWORDS => KEYWORDS ARE THE RESERVED WORD WHOSE MEANING IS ALREADY DEFINE IN THE COMPILER.(THERE ARE 36 KEYWORD IN PYTHON).

#PUNCTUATORS => ORGANIZE CODE IN BETTER WAY.  (),{},@,[],# etc.

#OPERATOR => OPERATOR IS SYMBOL THAT TELLS COMPUTER TO PERFORM MATHEMATICAL AND LOGICAL TASK(ADDITION , SUBSTRACTION ,MULTIPLICATION ,DIVISION,MODULUS ,FLOOR DIVISION).

#INPUT =>  STATEMENT IS USED TO ACEEPT VALUE FROM USER.(TAKING INPUT FROM USER INPUT FROM USER AND PRINTING IT).

#STRING INPUT
name = input("name :")
print(name)
#INT INPUT
age = int(input("age :"))
print(age)
#FLOAT INPUT
price = float(input("price :"))
print(float)
